### ISSUE TITLE
Live Code uses python kernel

### ISSUE THREAD

**Issue by PhiSpel** [hbrs-cse/Modellbildung-und-Simulation#479] opened 2023-01-10 13:18 UTC
This seems to be a known issue, see [here](https://hbrs-cse.github.io/Modellbildung-und-Simulation/00_einleitung/02_verwendung_dieses_buches.html#troubleshooting). However, I now do not get back to the octave kernel, even after reloading the page several times. In mybinder, it works just fine.

The same happens when I execute Live Code in my offline html pages

- [ ] Update the troubleshooting page
- [ ] Update jupyter-book if necessary

**Comment by PhiSpel** [comment] 2023-01-10 15:46
Maybe this is because we removed this line?

https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/8ff0d46c471c97e8c3257b2cc0e77417f2d258ff/.circleci/config.yml#L19

**Comment by joergbrech** [comment] 2023-01-10 18:27
I don't know what the problem is, but circle ci has nothing to do with the live code, just the generation of the static html. So that's not it...

**Comment by joergbrech** [comment] 2023-01-11 16:20
Probably related to https://github.com/executablebooks/jupyter-book/issues/1173

**Comment by PhiSpel** [comment] 2023-01-11 16:39
Try running an example repo with octave kernel

**Comment by joergbrech** [comment] 2023-01-11 22:55
> Probably related to [executablebooks/jupyter-book#1173](https://github.com/executablebooks/jupyter-book/issues/1173), [executablebooks/jupyter-book#90](https://github.com/executablebooks/jupyter-book/issues/90).
> 
> Possibly related to/caused by [executablebooks/thebe#349](https://github.com/executablebooks/thebe/issues/349)

It seems to me that specifically the last issue is what is causing our problems: 
 - Older jupyter-book versions use an older sphinx-thebe version 0.\*, which in turn uses a pre 0.6.0 thebe version. Here, the kernel is selected based on `kernelOptions.kernalName`. 
 - Newer jupyter-book versions use 0.1.\* sphinx-thebe which uses a thebe version>=0.6.0. According to the above issue, the kernel should be selected based on `kernelOptions.name`. 
- Our site is built with the latest jupyter-book version, but the kernel is still specified using `kernelName`:

https://github.com/hbrs-cse/Modellbildung-und-Simulation/blob/73d558be59f60911e9ac400f41b2147ccc33f907/intro.html#L915

So this is either a bug in jupyter-book or sphinx-thebe. I am guessing its the latter.

To test this hypothesis, we could update intro.html on our gh-pages branch. Usually I would strictly be against manually fiddling with our released site, but this line only affects stuff that is broken anyway...

**Comment by joergbrech** [comment] 2023-01-12 08:17
I tested this in a local build and my hypothesis was correct. This is a bug in `sphinx-thebe`, see https://github.com/executablebooks/sphinx-thebe/issues/59.

**Comment by joergbrech** [comment] 2023-01-12 08:18
Also, the troubleshooting on our site is outdated.

**Comment by PhiSpel** [comment] 2023-01-12 14:18
@joergbrech, awesome, thank you! I subscribed to your PR for sphinx-thebe, so once the new releases are out, we can update the versions over here.

**Comment by PhiSpel** [comment] 2023-01-17 11:51
@joergbrech we still need to wait for the release of jupyter-book using a sphinx-thebe release with your changes, correct?

**Comment by joergbrech** [comment] 2023-01-17 11:52
> @joergbrech we still need to wait for the release of jupyter-book using a sphinx-thebe release with your changes, correct?

yep

**Comment by joergbrech** [comment] 2023-02-08 07:54
> @joergbrech we still need to wait for the release of jupyter-book using a sphinx-thebe release with your changes, correct?

There has been a new release over at jupyter-book today: https://github.com/executablebooks/jupyter-book/releases/tag/v0.13.2. This latest release uses sphinx-thebe 0.2.1. In theory, bumping our jupyter-book version in requirements.txt should include the fix for this issue.

**Closed** 2023-02-08 09:38 UTC
Labels: bug
